[[data]]
"Proponents/ VIEW OF LIBERATION" = ''
"Attainable tattva\n(Rāmakantha)" = ''
"Attainable tattva\n(Trilocana)" = ''
"SAIVA TATTVAS" = 'śiva'

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Saktyadvaitavidins'
"Attainable tattva\n(Rāmakantha)" = 'śakti'
"Attainable tattva\n(Trilocana)" = 'śakti'
"SAIVA TATTVAS" = 'śakti'

[[data]]
"Proponents/ VIEW OF LIBERATION" = ''
"Attainable tattva\n(Rāmakantha)" = ''
"Attainable tattva\n(Trilocana)" = ''
"SAIVA TATTVAS" = 'Sadāśiva'

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Pravāha-nityēśvara-vādins (13)'
"Attainable tattva\n(Rāmakantha)" = ''
"Attainable tattva\n(Trilocana)" = 'Iśvara'
"SAIVA TATTVAS" = ''

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Being an Agent yet remaining subject to the control of God (9)'
"Attainable tattva\n(Rāmakantha)" = 'Iśvara'
"Attainable tattva\n(Trilocana)" = 'Iśvara'
"SAIVA TATTVAS" = 'Iśvara'

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Mahavratas (8)'
"Attainable tattva\n(Rāmakantha)" = 'Vidyā'
"Attainable tattva\n(Trilocana)" = 'Vidyā'
"SAIVA TATTVAS" = 'Vidyā'

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Avesavadins (20)'
"Attainable tattva\n(Rāmakantha)" = ''
"Attainable tattva\n(Trilocana)" = 'Mayã'
"SAIVA TATTVAS" = ''

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Utpattivadins (18)'
"Attainable tattva\n(Rāmakantha)" = ''
"Attainable tattva\n(Trilocana)" = 'Mayã'
"SAIVA TATTVAS" = 'Mayã'

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Pasupatas (19)'
"Attainable tattva\n(Rāmakantha)" = 'Mayã'
"Attainable tattva\n(Trilocana)" = 'Mayã'
"SAIVA TATTVAS" = ''

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Vaidika Pasupatas'
"Attainable tattva\n(Rāmakantha)" = ''
"Attainable tattva\n(Trilocana)" = 'Mayã'
"SAIVA TATTVAS" = ''

[[data]]
"Proponents/ VIEW OF LIBERATION" = ''
"Attainable tattva\n(Rāmakantha)" = ''
"Attainable tattva\n(Trilocana)" = ''
"SAIVA TATTVAS" = 'Kala, Aśuddhavidyā, Rāga, Kãla, Niyati'

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Pauranikas: Becoming a chief attendant (ganesvara) of the Lord or attaining the same world etc. (sãlokydi) as Him (7).'
"Attainable tattva\n(Rāmakantha)" = ''
"Attainable tattva\n(Trilocana)" = 'Puruṣa'
"SAIVA TATTVAS" = ''

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Vedānta (3)'
"Attainable tattva\n(Rāmakantha)" = 'Puruṣa'
"Attainable tattva\n(Trilocana)" = 'Puruṣa'
"SAIVA TATTVAS" = 'Puruṣa'

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Sabdabrahmavidins'
"Attainable tattva\n(Rāmakantha)" = 'Puruṣa'
"Attainable tattva\n(Trilocana)" = 'Puruṣa'
"SAIVA TATTVAS" = ''

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Vedānta (Parināmavada) (3)'
"Attainable tattva\n(Rāmakantha)" = ''
"Attainable tattva\n(Trilocana)" = 'Puruṣa'
"SAIVA TATTVAS" = ''

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Vedānta (Parināmavida) (3)'
"Attainable tattva\n(Rāmakantha)" = 'Prakr̥ti'
"Attainable tattva\n(Trilocana)" = ''
"SAIVA TATTVAS" = 'Prakr̥ti / Avyakta'

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Pañcarátras (4)'
"Attainable tattva\n(Rāmakantha)" = 'Prakr̥ti'
"Attainable tattva\n(Trilocana)" = 'Avyakta'
"SAIVA TATTVAS" = ''

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Sāṅkhyas (1)'
"Attainable tattva\n(Rāmakantha)" = 'Top of Guṇas'
"Attainable tattva\n(Trilocana)" = 'Top of Guṇas'
"SAIVA TATTVAS" = ''

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Pātanjalas (1)'
"Attainable tattva\n(Rāmakantha)" = ''
"Attainable tattva\n(Trilocana)" = 'Top of Guṇas'
"SAIVA TATTVAS" = ''

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Enjoyment of Sattva (2)'
"Attainable tattva\n(Rāmakantha)" = ''
"Attainable tattva\n(Trilocana)" = 'Guṇas'
"SAIVA TATTVAS" = 'Guṇas'

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Jains'
"Attainable tattva\n(Rāmakantha)" = 'Guṇas'
"Attainable tattva\n(Trilocana)" = 'Guṇas'
"Attainable tattva\n(Trilocana)" = 'Guṇas'
"SAIVA TATTVAS" = ''

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Naiyayikas, Vaisesikas (15)'
"Attainable tattva\n(Rāmakantha)" = 'Buddhi'
"Attainable tattva\n(Trilocana)" = 'Buddhi'
"SAIVA TATTVAS" = ''

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Buddhists (16)'
"Attainable tattva\n(Rāmakantha)" = 'Products (vrtti) of Buddhi'
"Attainable tattva\n(Trilocana)" = 'Buddhi'
"SAIVA TATTVAS" = 'Buddhi'

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Ahankāracaitanikas'
"Attainable tattva\n(Rāmakantha)" = 'Ahaṅkāra'
"Attainable tattva\n(Trilocana)" = 'Ahaṅkāra'
"SAIVA TATTVAS" = 'Ahankāra'

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Manascaitanikas'
"Attainable tattva\n(Rāmakantha)" = 'Manas'
"Attainable tattva\n(Trilocana)" = 'Manas'
"SAIVA TATTVAS" = 'Manas'

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Indriyacaitanikas'
"Attainable tattva\n(Rāmakantha)" = 'Indriyas'
"Attainable tattva\n(Trilocana)" = 'Indriyas'
"SAIVA TATTVAS" = 'Indriyas'

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Manu etc.'
"Attainable tattva\n(Rāmakantha)" = ''
"Attainable tattva\n(Trilocana)" = 'Tanmātras'
"SAIVA TATTVAS" = 'Tanmātras'

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Jaiminiya Karma-mimāmsakas'
"Attainable tattva\n(Rāmakantha)" = ''
"Attainable tattva\n(Trilocana)" = 'Tanmātras'
"SAIVA TATTVAS" = 'Tanmātras'

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Those who equate brahman with the cause of the elements and the Egg of Brahma (brahmanda)'
"Attainable tattva\n(Rāmakantha)" = 'Tanmātras'
"Attainable tattva\n(Trilocana)" = ''
"SAIVA TATTVAS" = 'Tanmātras'

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Becoming the same as the Treasury of Light (10)'
"Attainable tattva\n(Rāmakantha)" = ''
"Attainable tattva\n(Trilocana)" = 'Mahabhūtas'
"SAIVA TATTVAS" = 'Mahabhūtas'

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Going to a world in the stars having acquired a refined body and faculties (14)'
"Attainable tattva\n(Rāmakantha)" = ''
"Attainable tattva\n(Trilocana)" = 'Mahabhūtas'
"SAIVA TATTVAS" = 'Mahabhūtas'

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Kaulas'
"Attainable tattva\n(Rāmakantha)" = 'Mahabhūtas'
"Attainable tattva\n(Trilocana)" = 'Mahabhūtas'
"SAIVA TATTVAS" = 'Mahabhūtas'

[[data]]
"Proponents/ VIEW OF LIBERATION" = 'Carvãkas (17)'
"Attainable tattva\n(Rāmakantha)" = 'Mahabhūtas'
"Attainable tattva\n(Trilocana)" = 'Mahabhūtas'
"SAIVA TATTVAS" = 'Mahabhūtas'
